"""initial schema

Revision ID: 59d98933ff77
Revises: 
Create Date: 2026-07-23 19:31:02.918858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '59d98933ff77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('received', 'ingesting', 'ocr_complete', 'safety_blocked', 'extracted', 'validated', 'corrected', 'human_review', 'completed', 'failed', name='documentstatus', native_enum=False), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('human_review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_documents_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=40), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_audit_events_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('document_id', 'sequence_number', name='uq_audit_document_sequence')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_document_id'), ['document_id'], unique=False)

    op.create_table('document_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=True),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_status_history_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_status_history'))
    )
    with op.batch_alter_table('document_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_status_history_document_id'), ['document_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_address', sa.Text(), nullable=True),
    sa.Column('vendor_tax_id', sa.String(length=100), nullable=True),
    sa.Column('vendor_bank_account_masked', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=120), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('purchase_order_number', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('shipping', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('previous_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('credit_adjustment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('complexity_tier', sa.String(length=20), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('extraction_attempts', sa.Integer(), nullable=False),
    sa.Column('overall_ocr_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('field_confidence_json', sa.JSON(), nullable=True),
    sa.Column('line_items_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('raw_extraction_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_invoices_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_number'), ['invoice_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_vendor_name'), ['vendor_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_vendor_tax_id'), ['vendor_tax_id'], unique=False)

    op.create_table('safety_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('attack_type', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('expected_action', sa.String(length=30), nullable=False),
    sa.Column('reasons_json', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_safety_decisions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_decisions'))
    )
    with op.batch_alter_table('safety_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_decisions_document_id'), ['document_id'], unique=False)

    op.create_table('correction_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('requested_fields_json', sa.JSON(), nullable=False),
    sa.Column('changed_fields_json', sa.JSON(), nullable=False),
    sa.Column('unauthorized_changes_json', sa.JSON(), nullable=True),
    sa.Column('guardrail_passed', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_correction_history_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_correction_history_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correction_history'))
    )
    with op.batch_alter_table('correction_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_history_document_id'), ['document_id'], unique=False)

    op.create_table('rag_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('matched_vendor_id', sa.String(length=100), nullable=True),
    sa.Column('matched_legal_name', sa.String(length=255), nullable=True),
    sa.Column('top_distance', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('exact_checks_json', sa.JSON(), nullable=True),
    sa.Column('issues_json', sa.JSON(), nullable=True),
    sa.Column('recommended_action', sa.String(length=60), nullable=True),
    sa.Column('knowledge_base_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_rag_evidence_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_rag_evidence_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_evidence'))
    )
    with op.batch_alter_table('rag_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_evidence_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_evidence_status'), ['status'], unique=False)

    op.create_table('validation_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('validation_run', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_validation_issues_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_validation_issues_invoice_id_invoices'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_issues'))
    )
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_issues_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_issues_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_issues_severity'), ['severity'], unique=False)

    op.create_table('rag_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rag_evidence_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=100), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('distance', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rag_evidence_id'], ['rag_evidence.id'], name=op.f('fk_rag_candidates_rag_evidence_id_rag_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rag_candidates'))
    )
    with op.batch_alter_table('rag_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_candidates_rag_evidence_id'), ['rag_evidence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_candidates_rag_evidence_id'))

    op.drop_table('rag_candidates')
    with op.batch_alter_table('validation_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_issues_severity'))
        batch_op.drop_index(batch_op.f('ix_validation_issues_document_id'))
        batch_op.drop_index(batch_op.f('ix_validation_issues_code'))

    op.drop_table('validation_issues')
    with op.batch_alter_table('rag_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_evidence_status'))
        batch_op.drop_index(batch_op.f('ix_rag_evidence_document_id'))

    op.drop_table('rag_evidence')
    with op.batch_alter_table('correction_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_history_document_id'))

    op.drop_table('correction_history')
    with op.batch_alter_table('safety_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_decisions_document_id'))

    op.drop_table('safety_decisions')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_vendor_tax_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_vendor_name'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoices_document_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('document_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_status_history_document_id'))

    op.drop_table('document_status_history')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_document_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_documents_request_id'))

    op.drop_table('documents')
    # ### end Alembic commands ###