"""initial schema

Revision ID: 635ed925b1c1
Revises: 59d98933ff77
Create Date: 2026-07-23 19:34:01.301594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '635ed925b1c1'
down_revision: Union[str, None] = '59d98933ff77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###